title: <p align="center"> Achyuth Kakarla </p>
logo: /assets/img/logo.png
description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
   <a href="https://github.com/ACHYUTH10">GitHub</a>
  
  <br>   
  I'm working on SAP , My future developments will be on Data Science, 
  Big Data, Spark, Machine learning & NLP related problems.
  Worked with Product development teams with advanced concepts.
  Working in startup company.
  <br>
  </p>



theme: jekyll-theme-minimal
