title: <p align="center"> Achyuth Kakarla </p>
logo: /assets/img/Achyuth Photo (1).JPG
  <p align="center">
  <br>   
  I'm working on SAP , My future developments will be on Data Science, 
  Big Data, Spark, Machine learning & NLP related problems.
  Working in startup company.
  <br>
  </p>


theme: jekyll-theme-minimal
